driver=oracle.jdbc.driver.OracleDriver
url=jdbc:oracle:thin:@//172.16.180.49:1521/pdb_uat
username=uat_ime
password=uatime
changeLogFile=src/main/resources/config/liquibase/master.xml
#diffChangeLogFile=src/main/resources/config/liquibase/changelog/liquibase-tmp-diff.xml
referenceUrl=hibernate:spring:com.nicico.internal.sales.model,com.nicico.copper.oauth.common.model?dialect=org.hibernate.dialect.Oracle12cDialect
diffExcludeObjects=table:tbl_oa_.*,sequence:seq_oa_.*
