SELECT SYSDATE                                                            as D_ISSUE_DATE,

       RM.N_CUSTOMER_ID,
       CUS.C_NAME                                                         AS C_CUSTOMER_NAME,
       CUS.C_ECONOMIC_CODE,
       CUS.C_NATIONAL_CODE,
       '01/' || CUS.C_NATIONAL_CODE                                       AS CUSTOMER_NOSA_CODE,
       CUS.C_PHONE,
       CUS.C_REGISTER_NUMBER,
       CUS.C_POST_CODE,
       CUS.C_EMAIL,
       CUS.C_MOBILE,
       CUS.C_COORDINATOR,
       CUS.C_ADDRESS,
       COALESCE(TO_NUMBER(TBL.ID), 0)                                     AS TRADE_ID,
       TBL.COMMODITY_CODE,
       TBL.CONTRACT_DATE,
       RM.ID,
       RM.D_REMITTANCE_DATE,
       COALESCE(TO_CHAR(RM.D_VALIDITY_DATE, 'YYYY-MM-DD'), '1900-01-01')  AS D_VALIDITY_DATE,
       RM.N_LOADING_PORT_ID,
       RM.C_LOADING_PORT,
       RM.N_GOOD_ID,
       RM.C_GOOD_NAME,
       RM.C_PACKING_NAME,
       RM.C_LOT_NUMBER,
       RM.D_CONTRACT_DATE,
       RM.C_CONTRACT_NO,
       RM.C_SELLER_BROKER_NAME,
       RM.N_CASH_PERCENTAGE,
       RM.N_CREDIT_PERCENTAGE,
       RM.N_REMITTANCE_QUANTITY,
       RM.N_REMITTANCE_QUANTITY_CASH,
       RM.N_REMITTANCE_QUANTITY_CREDIT,
       RM.N_REMITTANCE_UNIT_PRICE_CASH,
       RM.N_REMITTANCE_UNIT_PRICE_CREDIT,
       RM.C_SETTLEMENT_TYPE_DESC,

       til.ID                                                             AS LC_ID,
       til.C_ISSUER_BANK_BRANCH_NAME,
       til.N_ISSUER_BANK_ID,
       til.C_ISSUER_BANK_NAME,
       til.C_ISSUER_BANK_CODE,
       til.N_TRADING_BANK_ID,
       til.C_TRADING_BANK_TITLE,
       til.C_TRADING_BRANCH_TITLE,
       til.C_LC_NO,
       til.D_LC_DATE,
       til.D_LC_EXPIRY_DATE,
       tipm.C_OFFER_DESCRIPTION,
       TIPM.C_PROFORMA_ISSUE_TYPE,
       tipm.N_TOTAL_VAT_AMOUNT,
       tipd.C_SALE_TYPE,
       tipd.N_JALAALI_YEAR,
       tipd.N_PAYMENT_DEFERRAL,
       TIPD.D_ORDER_DATE,


       COALESCE(TO_CHAR(RM.D_LC_EXPIRY_DATE, 'YYYY-MM-DD'), '1900-01-01') AS D_LC_EXPIRY_DATE,
       COALESCE(TO_NUMBER(RM.N_ISSUER_BANK_ID), 0)                        AS N_ISSUER_BANK_ID
FROM TBL_IME_TRADE TBL
         INNER JOIN T_INS_REMITTANCE_MASTER RM ON TO_NUMBER(TBL.ID) = TO_NUMBER(RM.N_TRADE_ID)
         INNER JOIN T_INS_REMITTANCE_GOOD_ITEM RGI ON TO_NUMBER(RM.ID) = TO_NUMBER(RGI.F_REMITTANCE_ID)
         INNER JOIN T_INS_CUSTOMER CUS ON N_CUSTOMER_ID = CUS.ID
         INNER JOIN T_INS_PERFORMA_MASTER TIPM ON TIPM.ID = rm.N_PROFORMA_MASTER_ID
         INNER JOIN T_INS_PERFORMA_DETAIL TIPD ON TIPD.ID = RM.N_PROFORMA_DETAIL_ID
         INNER JOIN T_INS_LC TIL ON til.ID = RM.N_LC_ID


WHERE TO_NUMBER(TBL.CURRENCY_CODE) = 1
  AND RM.C_PMS_ID IS NOT NULL;