MERGE INTO T_INS_LC lc
USING (
    SELECT
        pgi.F_PERFORMA_DETAIL_ID,
        SUM(pgi.N_CREDIT_QUANTITY) AS TOTAL_CREDIT_QUANTITY,
        SUM(pgi.N_CREDIT_AMOUNT + NVL(pgi.N_VAT_CREDIT_AMOUNT, 0)) AS TOTAL_FINAL_AMOUNT
    FROM T_INS_PERFORMA_GOOD_ITEM pgi
    GROUP BY pgi.F_PERFORMA_DETAIL_ID
) agg
ON (lc.N_PROFORMA_DETAIL_ID = agg.F_PERFORMA_DETAIL_ID)
WHEN MATCHED THEN UPDATE SET
                             lc.N_TOTAL_QUANTITY = NVL(agg.TOTAL_CREDIT_QUANTITY, 0),
                             lc.N_TOTAL_FINAL_AMOUNT = NVL(agg.TOTAL_FINAL_AMOUNT, 0);